# Generated by Django 4.0.5 on 2022-06-27 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('sort_number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField()),
                ('birthdate', models.DateField()),
                ('experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sort_number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('directions', models.ManyToManyField(related_name='directions', to='main.direction')),
            ],
        ),
    ]
